# General settings
dataset: "KITTI"
device: "cuda:0"
num_workers: 24                # Increased number of workers for faster data loading
cuda_visible_devices: "0"      # Using one GPU (adjust if needed)
wandb_project: "FusionLIVO->FlowNet"  # WandB project name

# Modality flags
use_camera: False
use_lidar: False
use_fusion: True

# DeepVO settings (used for paths and image preprocessing)
deepvo:
  image_dir: "/home/kavi/Datasets/KITTI_raw/kitti_data/sequences/"
  pose_dir: "/home/kavi/Datasets/KITTI_raw/kitti_data/poses_7dof/"
  calib_folder: "/home/kavi/Datasets/KITTI_raw/kitti_data/calib/"
  timestamp_folder: "/home/kavi/Datasets/KITTI_raw/kitti_data/timestamp_folder"
  train_video: ["00", "01", "02", "05", "08", "09"]  # Training sequences
  valid_video: ["04", "06", "07", "10"]              # Validation sequences
  resize_mode: "rescale"
  img_h: 64
  img_w: 900
  img_means: [-0.49866461753845215, -0.4985489547252655, -0.49856969714164734]
  img_stds: [0.0012165356893092394, 0.0012363927671685815, 0.001266363193280995]
  minus_point_5: True

# LoRCoN-LO settings (used for LiDAR data paths)
lorcon_lo:
  scan_folder: "/home/kavi/Datasets/KITTI_raw/kitti_data/scan"
  preprocessed_folder: "/home/kavi/Datasets/KITTI_raw/kitti_data/preprocessed_data/"
  relative_pose_folder: "/home/kavi/Datasets/KITTI_raw/kitti_data/relative_pose/"
  pose_folder: "/home/kavi/Datasets/KITTI_raw/kitti_data/poses/"
  calib_folder: "/home/kavi/Datasets/KITTI_raw/kitti_data/calib/"
  timestamp_folder: "/home/kavi/Datasets/KITTI_raw/kitti_data/timestamp_folder"
  image_width: 900
  image_height: 64
  fov_up: 3.0
  fov_down: -25.0
  proj_H: 64
  proj_W: 900
  max_range: 50
  depth_name: "depth"
  intensity_name: "intensity"
  normal_name: "normal"

# Fusion settings (optimized for PC1 with 16GB GPU and 80GB RAM)
fusion:
  batch_size: 8
  epochs: 10
  rnn_size: 5
  model_path: "models/fusion_model_best.pth"
  rnn_hidden_size: 256
  dropout: 0.7
  use_autocast: False
  use_grad_scaler: False
  use_augmentation: True
  w_rot: 1.0
  modalities:
    use_depth: True
    use_intensity: False
    use_normals: True
    use_rgb_low: False
  optim:
    opt: "Adam"
    lr: 0.0001  # Changed from 1e-4 to explicit float
    weight_decay: 0.001  # Changed from 1e-3 to explicit float
  scheduler:
    step_size: 3
    gamma: 0.1
  grad_clip:
    max_norm: 0.5
  early_stopping:
    patience: 3
    min_delta: 0.01